/* ============================================================
   CONTEÚDO — Panorama da Bíblia inteira (66 livros),
   a grande história (metanarrativa) e o método de estudo.
   Tudo em português. IDs estáveis (o progresso é salvo por ID).
   ============================================================ */

// Perguntas padrão que acompanham cada livro (além da específica).
window.PERGUNTAS_PADRAO = [
  { sufixo: 'q2', tipo: 'aplicacao', texto: 'O que este livro ensina sobre Deus — e o que isso muda na sua vida hoje?' },
  { sufixo: 'q3', tipo: 'oracao', texto: 'Escreva uma oração respondendo ao que você leu.' },
];
window.TIPOS_PERGUNTA = {
  observacao: 'Observação', interpretacao: 'Interpretação',
  aplicacao: 'Aplicação', pratica: 'Prática', oracao: 'Oração',
};

// ---------- Como estudar a Bíblia (método integrado) ----------
window.METODO = {
  titulo: 'Como estudar a Bíblia',
  intro: 'Estudar a Bíblia não é técnica complicada — é aprender a ouvir bem. Estes quatro passos servem para qualquer texto, do Gênesis ao Apocalipse. Use-os toda vez que abrir um livro aqui.',
  passos: [
    { n: 1, nome: 'Observar', cor: 'violeta', texto: 'O que o texto diz? Antes de interpretar, veja os fatos: quem fala, com quem, o que acontece, o que se repete. Leia devagar, sem pressa de concluir.' },
    { n: 2, nome: 'Interpretar', cor: 'azul', texto: 'O que o texto significa? Pergunte o que significava para os primeiros leitores, no contexto do livro e da história da salvação. Um texto nunca significa o que nunca significou.' },
    { n: 3, nome: 'Aplicar', cor: 'esmeralda', texto: 'O que isso muda em mim? Toda a Escritura é útil para ensinar, corrigir e formar (2 Tm 3:16). Procure uma verdade para crer, um pecado a deixar, uma atitude a tomar.' },
    { n: 4, nome: 'Orar', cor: 'ouro', texto: 'Responda a Deus. Transforme o que aprendeu em oração: adore pelo que Ele revelou, confesse, peça graça para obedecer. O estudo vira comunhão.' },
  ],
  dicas: [
    'Leia o livro inteiro antes de detalhar partes — veja o bosque antes das árvores.',
    'Todo livro aponta, de algum modo, para Jesus (Lc 24:27). Procure essa ligação.',
    'Anote suas respostas: escrever fixa o aprendizado e vira seu diário de fé.',
  ],
};

// ---------- A grande história (metanarrativa) ----------
window.HISTORIA = {
  titulo: 'A grande história',
  intro: 'A Bíblia são 66 livros, mas uma só história: como Deus, diante da queda do ser humano, cumpre a promessa de redimir um povo e restaurar toda a criação em Jesus. Entender esses seis atos ajuda a encaixar cada livro no todo.',
  atos: [
    { id: 'ato1', nome: '1. Criação', ref: 'Gênesis 1–2', ideia: 'Deus cria um mundo bom e o ser humano à sua imagem, para viver em comunhão com Ele.', texto: 'No princípio não há caos nem acaso: há um Deus que fala e ordena. Tudo é criado “bom”, e a humanidade recebe dignidade e propósito. Este é o mundo como Deus quis.' },
    { id: 'ato2', nome: '2. Queda', ref: 'Gênesis 3', ideia: 'O pecado entra pela desobediência e quebra a relação com Deus, com o próximo e com a criação.', texto: 'O ser humano decide ser deus de si mesmo. O resultado é vergonha, culpa, morte e um mundo em desordem. Toda dor que conhecemos nasce aqui — mas Deus já promete um libertador (Gn 3:15).' },
    { id: 'ato3', nome: '3. Israel — a promessa', ref: 'Gênesis 12 – Malaquias', ideia: 'Deus escolhe Abraão e forma um povo, por meio de quem abençoará todas as nações.', texto: 'De Abraão a Davi e aos profetas, Deus se compromete por aliança com um povo. A Lei mostra a santidade de Deus e a incapacidade humana; os profetas apontam para um Rei e um Salvador que viria. O Antigo Testamento termina em expectativa.' },
    { id: 'ato4', nome: '4. Cristo', ref: 'Mateus – João', ideia: 'Deus se faz homem em Jesus, que vive, morre e ressuscita para salvar.', texto: 'A promessa se cumpre. Jesus é o descendente prometido, o Rei, o Cordeiro. Na cruz Ele carrega o pecado; na ressurreição, vence a morte. Este é o centro de toda a história.' },
    { id: 'ato5', nome: '5. A Igreja — a missão', ref: 'Atos – Judas', ideia: 'Pelo Espírito, o evangelho se espalha e nasce a Igreja, enviada a todas as nações.', texto: 'O que foi prometido a Abraão acontece: a bênção alcança os povos. As cartas ensinam a Igreja a viver e crer enquanto espera a volta de Cristo.' },
    { id: 'ato6', nome: '6. A nova criação', ref: 'Apocalipse', ideia: 'Cristo volta, julga o mal e faz novas todas as coisas — Deus habita com o seu povo.', texto: 'A história não termina em ruína, mas em restauração: novo céu e nova terra, sem morte nem lágrimas. O jardim perdido vira uma cidade eterna. Deus com o seu povo, para sempre.' },
  ],
};

// ---------- Os 66 livros ----------
// Campos: id, nome, caps, autor, data, tema, chave, panorama, cristo, pergunta (observação específica)
window.BIBLIA = [
  { divisao: 'Pentateuco', testamento: 'Antigo Testamento', livros: [
    { id: 'gn', nome: 'Gênesis', caps: 50, autor: 'Moisés (tradicional)', data: '~1445–1405 a.C.',
      tema: 'As origens: criação, queda e o início da promessa.',
      chave: 'Gn 12:3 — "Em ti serão benditas todas as famílias da terra."',
      panorama: 'Do princípio de tudo à formação de uma família: criação, queda, dilúvio e Babel; depois Abraão, Isaque, Jacó e José. Deus faz uma aliança e promete um povo e uma bênção para as nações.',
      cristo: 'A descendência prometida a Abraão que abençoaria o mundo se cumpre em Jesus.',
      pergunta: 'O que a promessa de Deus a Abraão revela sobre o plano de salvação que atravessa toda a Bíblia?' },
    { id: 'ex', nome: 'Êxodo', caps: 40, autor: 'Moisés (tradicional)', data: '~1445 a.C.',
      tema: 'A libertação de Israel e a aliança no Sinai.',
      chave: 'Êx 6:7 — "Tomarei vós por meu povo e serei vosso Deus."',
      panorama: 'Deus liberta Israel da escravidão no Egito pela Páscoa e pelo mar, e no Sinai dá a Lei e o tabernáculo — para habitar no meio do seu povo.',
      cristo: 'A Páscoa e o cordeiro apontam para Cristo, o Cordeiro que nos liberta do pecado.',
      pergunta: 'O que a Páscoa e a travessia do mar ensinam sobre como Deus salva?' },
    { id: 'lv', nome: 'Levítico', caps: 27, autor: 'Moisés (tradicional)', data: '~1445 a.C.',
      tema: 'Como um povo pecador se aproxima de um Deus santo.',
      chave: 'Lv 19:2 — "Sede santos, porque eu, o Senhor vosso Deus, sou santo."',
      panorama: 'Sacrifícios, sacerdócio e leis de pureza mostram a seriedade do pecado e o preço de estar perto de Deus. Santidade não é opcional para quem é povo de Deus.',
      cristo: 'Os sacrifícios e o sumo sacerdote antecipam Jesus, sacrifício perfeito e sacerdote eterno.',
      pergunta: 'Por que era preciso sangue e sacrifício para se aproximar de Deus?' },
    { id: 'nm', nome: 'Números', caps: 36, autor: 'Moisés (tradicional)', data: '~1445–1405 a.C.',
      tema: 'A jornada pelo deserto e a fidelidade de Deus apesar da incredulidade.',
      chave: 'Nm 14:11 — "Até quando não crerá em mim este povo?"',
      panorama: 'Israel caminha do Sinai à terra prometida, mas a incredulidade custa 40 anos no deserto. Ainda assim, Deus sustenta e guia o seu povo.',
      cristo: 'A serpente de bronze levantada (Nm 21) é imagem de Cristo levantado na cruz (Jo 3:14).',
      pergunta: 'O que a incredulidade do povo em Números ensina sobre confiar em Deus?' },
    { id: 'dt', nome: 'Deuteronômio', caps: 34, autor: 'Moisés (tradicional)', data: '~1405 a.C.',
      tema: 'A renovação da aliança e o chamado a amar a Deus.',
      chave: 'Dt 6:5 — "Amarás o Senhor teu Deus de todo o teu coração."',
      panorama: 'À beira da terra prometida, Moisés relembra a Lei a uma nova geração e chama o povo a escolher a vida: amar, lembrar e obedecer a Deus.',
      cristo: 'Moisés anuncia um Profeta maior que viria (Dt 18:15) — cumprido em Jesus.',
      pergunta: 'O que significa, na prática, amar a Deus "de todo o coração"?' },
  ]},
  { divisao: 'Históricos', testamento: 'Antigo Testamento', livros: [
    { id: 'js', nome: 'Josué', caps: 24, autor: 'Josué / tradicional', data: '~1405–1385 a.C.',
      tema: 'A conquista da terra prometida pela fidelidade de Deus.',
      chave: 'Js 1:9 — "Sê forte e corajoso... o Senhor teu Deus é contigo."',
      panorama: 'Deus cumpre a promessa e dá a terra a Israel. A vitória vem pela obediência e pela presença de Deus, não pela força humana.',
      cristo: 'Josué (mesmo nome de Jesus) que dá "descanso" ao povo aponta para o descanso maior em Cristo.',
      pergunta: 'O que a conquista mostra sobre a relação entre a promessa de Deus e a obediência do povo?' },
    { id: 'jz', nome: 'Juízes', caps: 21, autor: 'Samuel (tradicional)', data: '~1043 a.C.',
      tema: 'O ciclo de pecado e a necessidade de um rei justo.',
      chave: 'Jz 21:25 — "Cada um fazia o que parecia reto aos seus olhos."',
      panorama: 'Sem liderança fiel, Israel entra num ciclo: peca, sofre, clama, é libertado — e recai. O caos revela a necessidade de um rei segundo o coração de Deus.',
      cristo: 'Os libertadores imperfeitos fazem ansiar pelo Libertador perfeito, Jesus.',
      pergunta: 'Que padrão se repete em Juízes, e o que ele revela sobre o coração humano?' },
    { id: 'rt', nome: 'Rute', caps: 4, autor: 'Desconhecido / Samuel (tradicional)', data: '~1000 a.C.',
      tema: 'A fidelidade e a redenção em meio ao cotidiano.',
      chave: 'Rt 1:16 — "O teu povo é o meu povo, e o teu Deus é o meu Deus."',
      panorama: 'Numa história de lealdade e graça, uma estrangeira, Rute, é acolhida e redimida por Boaz — e entra na linhagem do rei Davi.',
      cristo: 'Boaz, o "resgatador", prefigura Cristo, nosso Redentor; Rute está na genealogia de Jesus.',
      pergunta: 'Como a fidelidade de pessoas comuns se encaixa no plano maior de Deus?' },
    { id: '1sm', nome: '1 Samuel', caps: 31, autor: 'Samuel/Natã/Gade (tradicional)', data: '~930 a.C.',
      tema: 'De Samuel a Saul e Davi: Deus olha o coração.',
      chave: '1Sm 16:7 — "O Senhor olha para o coração."',
      panorama: 'Israel pede um rei; Saul fracassa por desobediência, e Deus escolhe Davi, um pastor de coração fiel. A história de Golias mostra a fé que confia em Deus.',
      cristo: 'Davi, o rei ungido segundo o coração de Deus, aponta para o Rei maior, Jesus.',
      pergunta: 'Que diferença de coração separa Saul de Davi?' },
    { id: '2sm', nome: '2 Samuel', caps: 24, autor: 'Tradicional', data: '~930 a.C.',
      tema: 'O reinado de Davi: grandeza, queda e a aliança eterna.',
      chave: '2Sm 7:16 — "O teu trono será estabelecido para sempre."',
      panorama: 'Davi unifica Israel e recebe a promessa de um trono eterno. Mas peca com Bate-Seba e colhe as consequências — sem perder a graça de Deus.',
      cristo: 'A promessa de um reino eterno para a casa de Davi cumpre-se em Jesus, filho de Davi.',
      pergunta: 'O que a aliança com Davi (cap. 7) revela sobre os planos de Deus?' },
    { id: '1rs', nome: '1 Reis', caps: 22, autor: 'Tradicional (Jeremias?)', data: '~560 a.C.',
      tema: 'Salomão, o templo e a divisão do reino.',
      chave: '1Rs 3:9 — "Dá ao teu servo um coração entendido."',
      panorama: 'Salomão constrói o templo e recebe sabedoria, mas o coração se desvia. Após ele, o reino se divide — e a idolatria começa a corroer o povo.',
      cristo: 'O templo, onde Deus habita, aponta para Jesus, que é o verdadeiro templo (Jo 2:19-21).',
      pergunta: 'Como até um rei sábio como Salomão se desvia — e o que isso adverte?' },
    { id: '2rs', nome: '2 Reis', caps: 25, autor: 'Tradicional (Jeremias?)', data: '~560 a.C.',
      tema: 'O declínio dos reinos e o exílio.',
      chave: '2Rs 17:13 — "Convertei-vos dos vossos maus caminhos."',
      panorama: 'Apesar de profetas como Elias e Eliseu, os dois reinos persistem na idolatria e caem: Israel para a Assíria, Judá para a Babilônia. O pecado tem consequências reais.',
      cristo: 'O fracasso dos reis intensifica a esperança no Rei fiel que viria, Jesus.',
      pergunta: 'Por que os reinos caem, apesar dos avisos dos profetas?' },
    { id: '1cr', nome: '1 Crônicas', caps: 29, autor: 'Esdras (tradicional)', data: '~430 a.C.',
      tema: 'A história de Davi relida para restaurar a esperança.',
      chave: '1Cr 16:34 — "Rendei graças ao Senhor, porque Ele é bom."',
      panorama: 'Escrito após o exílio, recorda as genealogias e o reinado de Davi, focando no culto e no templo — para reancorar a identidade do povo em Deus.',
      cristo: 'A ênfase na dinastia de Davi mantém viva a promessa messiânica.',
      pergunta: 'Por que relembrar a história ajuda um povo a recomeçar?' },
    { id: '2cr', nome: '2 Crônicas', caps: 36, autor: 'Esdras (tradicional)', data: '~430 a.C.',
      tema: 'O templo, os reis de Judá e o chamado ao arrependimento.',
      chave: '2Cr 7:14 — "Se o meu povo se humilhar e orar... eu sararei a sua terra."',
      panorama: 'De Salomão ao exílio, avalia os reis de Judá pela fidelidade a Deus e ao culto. Termina com um raio de esperança: o decreto para voltar e reconstruir.',
      cristo: 'A esperança de restauração aponta para a redenção plena em Cristo.',
      pergunta: 'O que 7:14 ensina sobre humildade e restauração?' },
    { id: 'ed', nome: 'Esdras', caps: 10, autor: 'Esdras', data: '~440 a.C.',
      tema: 'A volta do exílio e a reconstrução do templo.',
      chave: 'Ed 7:10 — "Esdras... se dispôs a buscar a Lei do Senhor e a praticá-la."',
      panorama: 'O povo retorna da Babilônia e reconstrói o templo em meio a oposição. Esdras ensina a Palavra e chama à pureza e à fidelidade.',
      cristo: 'A restauração do povo e do culto prepara o caminho para a vinda do Messias.',
      pergunta: 'O que a dedicação de Esdras à Palavra (7:10) ensina a você?' },
    { id: 'ne', nome: 'Neemias', caps: 13, autor: 'Neemias / Esdras', data: '~430 a.C.',
      tema: 'A reconstrução dos muros e a renovação do povo.',
      chave: 'Ne 8:10 — "A alegria do Senhor é a vossa força."',
      panorama: 'Neemias lidera a reconstrução dos muros de Jerusalém com oração e coragem, enfrentando oposição. O povo se reúne para ouvir e obedecer à Lei.',
      cristo: 'A restauração da cidade aponta para a cidade eterna que Cristo prepara.',
      pergunta: 'Como Neemias une oração e ação diante dos obstáculos?' },
    { id: 'et', nome: 'Ester', caps: 10, autor: 'Desconhecido', data: '~460 a.C.',
      tema: 'A providência de Deus para preservar o seu povo.',
      chave: 'Et 4:14 — "Quem sabe se para tempo como este chegaste ao reino?"',
      panorama: 'Sem citar o nome de Deus, o livro mostra sua mão invisível: Ester arrisca a vida e salva os judeus de um extermínio. Deus governa os bastidores.',
      cristo: 'A preservação do povo mantém viva a linhagem por onde viria o Salvador.',
      pergunta: 'Onde você percebe a providência de Deus mesmo quando Ele parece silencioso?' },
  ]},
  { divisao: 'Poéticos e Sabedoria', testamento: 'Antigo Testamento', livros: [
    { id: 'jo', nome: 'Jó', caps: 42, autor: 'Desconhecido', data: 'incerta (muito antigo)',
      tema: 'O sofrimento do justo e a soberania de Deus.',
      chave: 'Jó 42:5 — "Eu te conhecia só de ouvir, mas agora os meus olhos te veem."',
      panorama: 'Jó, um homem justo, perde tudo e luta com o porquê do sofrimento. Deus não explica cada dor, mas se revela — e isso basta. A fé cresce no encontro com Deus.',
      cristo: 'O clamor de Jó por um mediador (9:33) encontra resposta em Cristo, nosso Mediador.',
      pergunta: 'O que muda em Jó quando ele encontra a Deus, mesmo sem receber explicações?' },
    { id: 'sl', nome: 'Salmos', caps: 150, autor: 'Davi e outros', data: '~1000–430 a.C.',
      tema: 'O livro de orações e louvores do povo de Deus.',
      chave: 'Sl 23:1 — "O Senhor é o meu pastor, nada me faltará."',
      panorama: 'Cânticos para toda emoção humana: alegria, medo, culpa, gratidão, desespero e esperança. Ensinam a levar tudo a Deus com honestidade e fé.',
      cristo: 'Muitos salmos falam profeticamente de Cristo — seu sofrimento, morte e reinado.',
      pergunta: 'Qual salmo fala com a sua situação hoje, e o que ele te ensina a orar?' },
    { id: 'pv', nome: 'Provérbios', caps: 31, autor: 'Salomão e outros', data: '~950–700 a.C.',
      tema: 'A sabedoria para viver bem diante de Deus.',
      chave: 'Pv 1:7 — "O temor do Senhor é o princípio do conhecimento."',
      panorama: 'Ditados práticos sobre trabalho, fala, dinheiro, amizade e caráter. Sabedoria bíblica é viver a vida real à luz de Deus.',
      cristo: 'A Sabedoria personificada (cap. 8) aponta para Cristo, "a sabedoria de Deus" (1Co 1:24).',
      pergunta: 'Que área da sua vida mais precisa da sabedoria que começa no temor do Senhor?' },
    { id: 'ec', nome: 'Eclesiastes', caps: 12, autor: 'Salomão (tradicional)', data: '~935 a.C.',
      tema: 'O vazio da vida sem Deus e o sentido n’Ele.',
      chave: 'Ec 12:13 — "Teme a Deus e guarda os seus mandamentos."',
      panorama: 'O Pregador testa prazer, trabalho e sabedoria, e conclui: sem Deus, tudo é "vaidade". O sentido não está debaixo do sol, mas acima dele.',
      cristo: 'A busca por sentido só se sacia em Cristo, em quem estão todos os tesouros (Cl 2:3).',
      pergunta: 'Onde você já buscou sentido "debaixo do sol" e não encontrou?' },
    { id: 'ct', nome: 'Cantares', caps: 8, autor: 'Salomão', data: '~950 a.C.',
      tema: 'A beleza e a dignidade do amor.',
      chave: 'Ct 8:7 — "As muitas águas não podem apagar o amor."',
      panorama: 'Um poema que celebra o amor entre marido e mulher como dom bom de Deus, com ternura, desejo e compromisso.',
      cristo: 'Muitos leem o amor fiel do livro como retrato do amor de Cristo pela Igreja.',
      pergunta: 'O que o livro ensina sobre o amor como presente de Deus?' },
  ]},
  { divisao: 'Profetas Maiores', testamento: 'Antigo Testamento', livros: [
    { id: 'is', nome: 'Isaías', caps: 66, autor: 'Isaías', data: '~700–680 a.C.',
      tema: 'Juízo e salvação: o Santo de Israel e o Servo sofredor.',
      chave: 'Is 53:5 — "Ele foi ferido pelas nossas transgressões."',
      panorama: 'Isaías adverte sobre o juízo, mas anuncia esperança gloriosa: um Messias, o Servo que sofre pelo povo, e uma restauração que alcança todas as nações.',
      cristo: 'O Servo sofredor de Isaías 53 é o retrato mais claro da cruz de Jesus.',
      pergunta: 'O que Isaías 53 revela, séculos antes, sobre o que Jesus faria?' },
    { id: 'jr', nome: 'Jeremias', caps: 52, autor: 'Jeremias', data: '~627–580 a.C.',
      tema: 'O chamado ao arrependimento e a promessa de uma nova aliança.',
      chave: 'Jr 31:33 — "Porei a minha Lei no seu interior e a escreverei no seu coração."',
      panorama: 'O "profeta chorão" prega fielmente enquanto Judá caminha para o exílio. Em meio ao juízo, promete uma nova aliança que muda o coração.',
      cristo: 'A nova aliança prometida se inaugura no sangue de Jesus (Lc 22:20).',
      pergunta: 'Por que era preciso uma aliança que mudasse o coração, e não só as regras?' },
    { id: 'lm', nome: 'Lamentações', caps: 5, autor: 'Jeremias (tradicional)', data: '~586 a.C.',
      tema: 'O luto pela cidade caída e a esperança na misericórdia.',
      chave: 'Lm 3:22-23 — "As misericórdias do Senhor... se renovam cada manhã."',
      panorama: 'Poemas de lamento pela destruição de Jerusalém. No meio da dor mais funda, brilha a certeza de que a fidelidade de Deus não acaba.',
      cristo: 'A misericórdia que não se esgota se encarna em Cristo, homem de dores.',
      pergunta: 'Como é possível lamentar com sinceridade e ainda confiar em Deus?' },
    { id: 'ez', nome: 'Ezequiel', caps: 48, autor: 'Ezequiel', data: '~593–571 a.C.',
      tema: 'A glória de Deus, o juízo e a promessa de vida nova.',
      chave: 'Ez 36:26 — "Dar-vos-ei um coração novo."',
      panorama: 'Por visões impressionantes, Ezequiel mostra a glória de Deus deixando e depois voltando ao templo, e promete ressuscitar um povo morto (os ossos secos).',
      cristo: 'A promessa de coração novo e Espírito cumpre-se em Cristo e no Pentecostes.',
      pergunta: 'O que a visão dos ossos secos (cap. 37) ensina sobre o poder de Deus de dar vida?' },
    { id: 'dn', nome: 'Daniel', caps: 12, autor: 'Daniel', data: '~530 a.C.',
      tema: 'A fidelidade no exílio e a soberania de Deus sobre a história.',
      chave: 'Dn 2:44 — "O Deus do céu levantará um reino que não será jamais destruído."',
      panorama: 'Daniel e seus amigos permanecem fiéis num império pagão. Visões revelam que, por trás dos impérios, Deus reina e estabelecerá um reino eterno.',
      cristo: 'O "Filho do Homem" que recebe um reino eterno (cap. 7) é título que Jesus toma para si.',
      pergunta: 'Como manter a fidelidade a Deus num ambiente que pressiona contra a fé?' },
  ]},
  { divisao: 'Profetas Menores', testamento: 'Antigo Testamento', livros: [
    { id: 'os', nome: 'Oseias', caps: 14, autor: 'Oseias', data: '~750 a.C.',
      tema: 'O amor fiel de Deus por um povo infiel.',
      chave: 'Os 6:6 — "Misericórdia quero, e não sacrifício."',
      panorama: 'O casamento de Oseias com uma mulher infiel vira parábola viva: assim é o amor de Deus, que não desiste do povo adúltero.',
      cristo: 'O amor que busca e restaura o infiel se revela plenamente em Jesus.',
      pergunta: 'O que o amor persistente de Deus em Oseias revela sobre a graça?' },
    { id: 'jl', nome: 'Joel', caps: 3, autor: 'Joel', data: 'incerta',
      tema: 'O dia do Senhor e a promessa do Espírito.',
      chave: 'Jl 2:28 — "Derramarei o meu Espírito sobre toda a carne."',
      panorama: 'Uma praga de gafanhotos torna-se sinal do "dia do Senhor". Joel chama ao arrependimento e promete o derramar do Espírito.',
      cristo: 'A promessa do Espírito cumpre-se no Pentecostes (At 2), pela obra de Cristo.',
      pergunta: 'O que significa um arrependimento "de coração, e não só de roupas rasgadas" (2:13)?' },
    { id: 'am', nome: 'Amós', caps: 9, autor: 'Amós', data: '~760 a.C.',
      tema: 'Justiça social e verdadeira adoração.',
      chave: 'Am 5:24 — "Corra o juízo como as águas, e a justiça como ribeiro perene."',
      panorama: 'Amós denuncia a religião hipócrita que oprime o pobre. Deus não aceita culto sem justiça.',
      cristo: 'A justiça que Deus exige realiza-se em Cristo, justo e defensor do oprimido.',
      pergunta: 'Como sua fé se conecta (ou não) com justiça e cuidado pelo próximo?' },
    { id: 'ob', nome: 'Obadias', caps: 1, autor: 'Obadias', data: '~586 a.C.',
      tema: 'O juízo sobre o orgulho e a certeza de que Deus reina.',
      chave: 'Ob 1:15 — "Como fizeste, assim se fará contigo."',
      panorama: 'O menor livro do AT anuncia juízo sobre Edom por sua soberba e crueldade contra Israel — e afirma que o reino é do Senhor.',
      cristo: 'A vitória final do reino de Deus consuma-se no reinado de Cristo.',
      pergunta: 'De que formas o orgulho cega uma pessoa ou um povo?' },
    { id: 'jn', nome: 'Jonas', caps: 4, autor: 'Jonas', data: '~760 a.C.',
      tema: 'A misericórdia de Deus alcança até os inimigos.',
      chave: 'Jn 4:2 — "Sabia que és Deus clemente e misericordioso."',
      panorama: 'Jonas foge do chamado de pregar a Nínive porque não quer que os inimigos sejam poupados. Deus o corrige e mostra seu amor pelas nações.',
      cristo: 'Jesus vê no "sinal de Jonas" (3 dias) uma imagem de sua morte e ressurreição (Mt 12:40).',
      pergunta: 'Existe alguém que você resiste em ver alcançado pela graça de Deus?' },
    { id: 'mq', nome: 'Miquéias', caps: 7, autor: 'Miquéias', data: '~700 a.C.',
      tema: 'Justiça, misericórdia e humildade diante de Deus.',
      chave: 'Mq 6:8 — "Pratica a justiça, ama a misericórdia e anda humildemente com o teu Deus."',
      panorama: 'Miquéias denuncia a corrupção e anuncia esperança: de Belém viria o governante de Israel.',
      cristo: 'A profecia de Belém (5:2) cumpre-se no nascimento de Jesus.',
      pergunta: 'O que Miquéias 6:8 define como o essencial que Deus pede de você?' },
    { id: 'na', nome: 'Naum', caps: 3, autor: 'Naum', data: '~650 a.C.',
      tema: 'O juízo de Deus sobre a opressão.',
      chave: 'Na 1:7 — "O Senhor é bom, uma fortaleza no dia da angústia."',
      panorama: 'Nínive, que se arrependera em Jonas, voltou à crueldade. Naum anuncia seu fim: Deus é paciente, mas não deixa a maldade impune.',
      cristo: 'O Deus justo que julga o mal e protege os seus revela-se em Cristo, Juiz e Refúgio.',
      pergunta: 'Como equilibrar a bondade e a justiça de Deus na sua compreensão d’Ele?' },
    { id: 'hc', nome: 'Habacuque', caps: 3, autor: 'Habacuque', data: '~605 a.C.',
      tema: 'Da dúvida à confiança: o justo viverá pela fé.',
      chave: 'Hc 2:4 — "O justo viverá pela sua fé."',
      panorama: 'Habacuque questiona Deus sobre a injustiça. A resposta o leva da queixa à adoração: confiar em Deus mesmo quando tudo parece dar errado.',
      cristo: '"O justo viverá pela fé" torna-se base do evangelho em Romanos e Gálatas.',
      pergunta: 'Como levar suas dúvidas honestas a Deus sem perder a confiança n’Ele?' },
    { id: 'sf', nome: 'Sofonias', caps: 3, autor: 'Sofonias', data: '~630 a.C.',
      tema: 'O dia do Senhor e a alegria da restauração.',
      chave: 'Sf 3:17 — "O Senhor... se alegrará em ti com cânticos."',
      panorama: 'Anuncia juízo, mas termina com uma das imagens mais ternas da Bíblia: Deus cantando de alegria sobre o seu povo restaurado.',
      cristo: 'A alegria de Deus por um povo salvo cumpre-se pela redenção em Cristo.',
      pergunta: 'O que muda em você ao imaginar Deus se alegrando sobre o seu povo?' },
    { id: 'ag', nome: 'Ageu', caps: 2, autor: 'Ageu', data: '~520 a.C.',
      tema: 'Prioridades: reconstruir a casa de Deus.',
      chave: 'Ag 1:4 — "É tempo de habitardes em casas forradas, enquanto esta casa está deserta?"',
      panorama: 'O povo, de volta do exílio, cuidava de si e negligenciava o templo. Ageu os desafia a colocar Deus em primeiro lugar.',
      cristo: 'A glória futura do templo aponta para Cristo, presença de Deus entre nós.',
      pergunta: 'Que "casa própria" tem tomado o lugar que pertence a Deus na sua vida?' },
    { id: 'zc', nome: 'Zacarias', caps: 14, autor: 'Zacarias', data: '~520 a.C.',
      tema: 'Encorajamento pela esperança messiânica.',
      chave: 'Zc 9:9 — "Eis que o teu rei vem a ti... humilde, montado num jumento."',
      panorama: 'Por visões, Zacarias encoraja os que reconstroem o templo e aponta, com detalhes, para o Rei que viria.',
      cristo: 'Profecias como a entrada humilde do Rei (9:9) cumprem-se em Jesus no Domingo de Ramos.',
      pergunta: 'Como a esperança no que Deus prometeu sustenta você no presente?' },
    { id: 'ml', nome: 'Malaquias', caps: 4, autor: 'Malaquias', data: '~430 a.C.',
      tema: 'O último apelo antes de 400 anos de silêncio.',
      chave: 'Ml 3:1 — "Eis que envio o meu mensageiro."',
      panorama: 'Deus confronta a religião fria e desonesta do povo e promete enviar um mensageiro para preparar o caminho do Senhor.',
      cristo: 'O mensageiro anunciado é João Batista, que prepara a chegada de Jesus.',
      pergunta: 'Onde a sua fé corre risco de virar rotina fria, como a do povo em Malaquias?' },
  ]},
  { divisao: 'Evangelhos', testamento: 'Novo Testamento', livros: [
    { id: 'mt', nome: 'Mateus', caps: 28, autor: 'Mateus (Levi)', data: '~60–70 d.C.',
      tema: 'Jesus, o Rei prometido, cumprimento das Escrituras.',
      chave: 'Mt 1:23 — "Emanuel... Deus conosco."',
      panorama: 'Escrito com olhos judeus, mostra Jesus como o Messias que cumpre as profecias. Traz o Sermão do Monte e a Grande Comissão.',
      cristo: 'Todo o livro apresenta Jesus como o Rei do reino dos céus.',
      pergunta: 'Que ensino do Sermão do Monte (caps. 5–7) mais confronta você?' },
    { id: 'mc', nome: 'Marcos', caps: 16, autor: 'João Marcos', data: '~55–65 d.C.',
      tema: 'Jesus, o Servo que age com poder e serve até a morte.',
      chave: 'Mc 10:45 — "O Filho do Homem veio... para servir e dar a sua vida em resgate."',
      panorama: 'O evangelho mais curto e dinâmico, cheio de ação. Mostra Jesus servindo, curando e caminhando para a cruz.',
      cristo: 'Apresenta Jesus como o Servo sofredor que dá a vida pelos muitos.',
      pergunta: 'O que significa seguir um Rei que veio para servir, e não ser servido?' },
    { id: 'lc', nome: 'Lucas', caps: 24, autor: 'Lucas', data: '~60–62 d.C.',
      tema: 'Jesus, o Salvador de todos — pobres, perdidos e excluídos.',
      chave: 'Lc 19:10 — "O Filho do Homem veio buscar e salvar o perdido."',
      panorama: 'Escrito com cuidado de historiador, destaca a compaixão de Jesus pelos marginalizados e a alegria da salvação. Traz o filho pródigo e o bom samaritano.',
      cristo: 'Mostra Jesus como o Salvador cheio de graça para todos os povos.',
      pergunta: 'Quem são os "perdidos" que Jesus buscaria hoje, e como você os enxerga?' },
    { id: 'jo_ev', nome: 'João', caps: 21, autor: 'João, o apóstolo', data: '~85–90 d.C.',
      tema: 'Jesus, o Filho de Deus — para que creiais e tenhais vida.',
      chave: 'Jo 20:31 — "Estas coisas foram escritas para que creiais... e tenhais vida."',
      panorama: 'Por sinais e discursos ("Eu sou..."), João revela Jesus como Deus encarnado. Profundo e pessoal, chama à fé e à vida eterna.',
      cristo: 'Declara abertamente que Jesus é o Verbo, Deus feito carne.',
      pergunta: 'O que os "Eu sou" de Jesus (pão, luz, caminho...) revelam sobre quem Ele é para você?' },
  ]},
  { divisao: 'História da Igreja', testamento: 'Novo Testamento', livros: [
    { id: 'at', nome: 'Atos', caps: 28, autor: 'Lucas', data: '~62 d.C.',
      tema: 'O evangelho avança pelo poder do Espírito.',
      chave: 'At 1:8 — "Recebereis poder... e sereis minhas testemunhas até os confins da terra."',
      panorama: 'De Jerusalém a Roma, o Espírito nasce a Igreja e impulsiona a missão. Pedro e depois Paulo levam o evangelho aos judeus e gentios.',
      cristo: 'Jesus ressurreto continua sua obra pela Igreja, no poder do Espírito.',
      pergunta: 'O que Atos ensina sobre o papel do Espírito e da Igreja na missão?' },
  ]},
  { divisao: 'Cartas de Paulo', testamento: 'Novo Testamento', livros: [
    { id: 'rm', nome: 'Romanos', caps: 16, autor: 'Paulo', data: '~57 d.C.',
      tema: 'O evangelho explicado: justificação pela fé.',
      chave: 'Rm 1:16 — "O evangelho é o poder de Deus para a salvação de todo o que crê."',
      panorama: 'A exposição mais completa do evangelho: todos pecaram, mas somos justificados pela fé em Cristo, com vida nova pelo Espírito e segurança no amor de Deus.',
      cristo: 'Cristo é o centro: sua morte e ressurreição são a base da salvação.',
      pergunta: 'O que significa, para você, ser "justificado pela fé, e não pelas obras"?' },
    { id: '1co', nome: '1 Coríntios', caps: 16, autor: 'Paulo', data: '~55 d.C.',
      tema: 'O evangelho aplicado aos problemas da igreja.',
      chave: '1Co 13:13 — "O maior destes é o amor."',
      panorama: 'Paulo corrige divisões, imoralidade e mau uso dos dons numa igreja cheia de problemas — sempre à luz da cruz e do amor.',
      cristo: 'Cristo crucificado é a sabedoria e o poder de Deus contra a arrogância humana.',
      pergunta: 'Como o "capítulo do amor" (13) confronta a forma como você trata os outros?' },
    { id: '2co', nome: '2 Coríntios', caps: 13, autor: 'Paulo', data: '~56 d.C.',
      tema: 'Força na fraqueza e o ministério da reconciliação.',
      chave: '2Co 12:9 — "A minha graça te basta, porque o poder se aperfeiçoa na fraqueza."',
      panorama: 'Paulo defende seu ministério com franqueza e vulnerabilidade, mostrando que Deus age poderosamente através de vasos frágeis.',
      cristo: 'Em Cristo, Deus nos reconcilia consigo e nos faz embaixadores dessa reconciliação.',
      pergunta: 'Onde a sua fraqueza pode se tornar espaço para o poder de Deus?' },
    { id: 'gl', nome: 'Gálatas', caps: 6, autor: 'Paulo', data: '~48–49 d.C.',
      tema: 'A liberdade do evangelho contra o legalismo.',
      chave: 'Gl 2:16 — "O homem não é justificado por obras da lei, mas pela fé em Cristo."',
      panorama: 'Paulo combate com firmeza quem misturava a lei ao evangelho. Somos salvos pela graça e vivemos pelo Espírito, não pela carne.',
      cristo: 'Cristo nos resgatou da maldição da lei, tornando-se maldição por nós (3:13).',
      pergunta: 'Onde você tenta "completar" a graça com esforço próprio?' },
    { id: 'ef', nome: 'Efésios', caps: 6, autor: 'Paulo', data: '~60–62 d.C.',
      tema: 'A graça de Deus e a Igreja como corpo de Cristo.',
      chave: 'Ef 2:8 — "Pela graça sois salvos, por meio da fé."',
      panorama: 'Metade doutrina, metade prática: quem somos em Cristo e como isso transforma casamento, trabalho e a batalha espiritual.',
      cristo: 'Cristo é a cabeça da Igreja e a fonte de toda bênção espiritual.',
      pergunta: 'O que muda ao lembrar que a salvação é dom de Deus, "não de obras" (2:9)?' },
    { id: 'fp', nome: 'Filipenses', caps: 4, autor: 'Paulo', data: '~61 d.C.',
      tema: 'A alegria em Cristo em qualquer circunstância.',
      chave: 'Fp 4:4 — "Alegrai-vos sempre no Senhor."',
      panorama: 'Preso, Paulo transborda alegria. Ensina a humildade de Cristo, o contentamento e a paz que guarda o coração.',
      cristo: 'O hino de Filipenses 2 mostra Cristo que se humilha e é exaltado.',
      pergunta: 'O que costuma roubar sua alegria, e o que Filipenses responde a isso?' },
    { id: 'cl', nome: 'Colossenses', caps: 4, autor: 'Paulo', data: '~60–62 d.C.',
      tema: 'A supremacia e a suficiência de Cristo.',
      chave: 'Cl 1:18 — "Para que em tudo tenha a preeminência."',
      panorama: 'Contra falsos ensinos, Paulo exalta Cristo como Senhor de toda a criação e suficiente para tudo. Nada precisa ser acrescentado a Ele.',
      cristo: 'Cristo é a imagem do Deus invisível, em quem habita toda a plenitude.',
      pergunta: 'O que você é tentado a acrescentar a Cristo como se Ele não bastasse?' },
    { id: '1ts', nome: '1 Tessalonicenses', caps: 5, autor: 'Paulo', data: '~51 d.C.',
      tema: 'Viver na esperança da volta de Cristo.',
      chave: '1Ts 4:16 — "O Senhor descerá do céu."',
      panorama: 'Paulo encoraja uma igreja jovem a crescer no amor e na santidade, consolando-a com a certeza da volta de Jesus e da ressurreição.',
      cristo: 'A esperança da vinda de Cristo molda a vida presente do crente.',
      pergunta: 'Como a certeza da volta de Jesus muda a forma como você vive hoje?' },
    { id: '2ts', nome: '2 Tessalonicenses', caps: 3, autor: 'Paulo', data: '~51 d.C.',
      tema: 'Firmeza diante da confusão sobre o fim.',
      chave: '2Ts 3:13 — "Não vos canseis de fazer o bem."',
      panorama: 'Corrige mal-entendidos sobre a volta de Cristo e chama à perseverança no trabalho e no bem enquanto se espera.',
      cristo: 'A esperança em Cristo não gera preguiça, mas fidelidade constante.',
      pergunta: 'Como esperar a volta de Cristo sem parar de "fazer o bem" no dia a dia?' },
    { id: '1tm', nome: '1 Timóteo', caps: 6, autor: 'Paulo', data: '~63 d.C.',
      tema: 'Como conduzir a igreja com sã doutrina.',
      chave: '1Tm 3:15 — "A casa de Deus... coluna e firmeza da verdade."',
      panorama: 'Paulo orienta o jovem líder Timóteo sobre liderança, ensino saudável e vida piedosa na igreja.',
      cristo: 'Cristo Jesus veio ao mundo para salvar os pecadores (1:15).',
      pergunta: 'O que caracteriza um ensino e uma vida realmente "saudáveis" na fé?' },
    { id: '2tm', nome: '2 Timóteo', caps: 4, autor: 'Paulo', data: '~66–67 d.C.',
      tema: 'As últimas palavras: guardar a fé até o fim.',
      chave: '2Tm 4:7 — "Combati o bom combate, completei a carreira, guardei a fé."',
      panorama: 'A carta final de Paulo, perto da morte. Chama Timóteo a perseverar, pregar a Palavra e não se envergonhar do evangelho.',
      cristo: 'A fidelidade a Cristo até o fim recebe "a coroa da justiça".',
      pergunta: 'Que "bom combate" você está travando agora, e o que é preciso para terminá-lo bem?' },
    { id: 'tt', nome: 'Tito', caps: 3, autor: 'Paulo', data: '~63 d.C.',
      tema: 'A fé verdadeira produz boas obras.',
      chave: 'Tt 2:11 — "A graça de Deus... ensina a viver de modo sensato e justo."',
      panorama: 'Paulo instrui Tito a organizar as igrejas de Creta e mostra como a graça de Deus transforma o caráter e a conduta.',
      cristo: 'A graça que salva é a mesma que nos ensina a viver bem.',
      pergunta: 'Como a graça (não o medo) é o que realmente muda o comportamento?' },
    { id: 'fm', nome: 'Filemom', caps: 1, autor: 'Paulo', data: '~60–62 d.C.',
      tema: 'O evangelho que reconcilia e perdoa.',
      chave: 'Fm 1:16 — "Já não como escravo... mas como irmão amado."',
      panorama: 'Paulo intercede por Onésimo, escravo fugitivo agora convertido, pedindo a Filemom que o receba como irmão. O evangelho reordena relações.',
      cristo: 'Paulo assume a dívida de Onésimo — retrato do que Cristo fez por nós.',
      pergunta: 'Que relação sua precisa da reconciliação e do perdão que o evangelho gera?' },
  ]},
  { divisao: 'Cartas Gerais', testamento: 'Novo Testamento', livros: [
    { id: 'hb', nome: 'Hebreus', caps: 13, autor: 'Desconhecido', data: '~65–70 d.C.',
      tema: 'A superioridade e a suficiência de Cristo.',
      chave: 'Hb 12:2 — "Olhando para Jesus, autor e consumador da fé."',
      panorama: 'Mostra que Cristo é superior a tudo do Antigo Testamento — anjos, Moisés, sacerdotes, sacrifícios. Chama a perseverar na fé sem retroceder.',
      cristo: 'Cristo é o sumo sacerdote perfeito e o sacrifício final e definitivo.',
      pergunta: 'Por que "olhar para Jesus" é o segredo para perseverar na fé?' },
    { id: 'tg', nome: 'Tiago', caps: 5, autor: 'Tiago, irmão de Jesus', data: '~45–50 d.C.',
      tema: 'A fé viva se prova em obras.',
      chave: 'Tg 1:22 — "Sede praticantes da palavra, e não somente ouvintes."',
      panorama: 'Uma carta prática e direta sobre fala, riqueza, provações e favoritismo. A fé genuína aparece na vida, não só nas palavras.',
      cristo: 'Reflete os ensinos de Jesus, especialmente o Sermão do Monte, na vida diária.',
      pergunta: 'Onde a sua fé precisa virar prática, e não só concordância?' },
    { id: '1pe', nome: '1 Pedro', caps: 5, autor: 'Pedro', data: '~62–64 d.C.',
      tema: 'Esperança e santidade em meio ao sofrimento.',
      chave: '1Pe 1:3 — "Nos regenerou para uma viva esperança."',
      panorama: 'Escreve a cristãos perseguidos, chamando-os a viver com esperança, santidade e amor, seguindo o exemplo de Cristo no sofrimento.',
      cristo: 'Cristo sofreu por nós, deixando exemplo e abrindo o caminho da esperança.',
      pergunta: 'Como manter a esperança e a fé quando a vida cristã custa caro?' },
    { id: '2pe', nome: '2 Pedro', caps: 3, autor: 'Pedro', data: '~64–67 d.C.',
      tema: 'Crescer na graça e resistir aos falsos mestres.',
      chave: '2Pe 3:18 — "Crescei na graça e no conhecimento de nosso Senhor."',
      panorama: 'Pedro adverte contra falsos ensinos e o descrédito da volta de Cristo, chamando a crescer no verdadeiro conhecimento de Deus.',
      cristo: 'A promessa da volta de Cristo é certa; Ele apenas é paciente para que todos se arrependam.',
      pergunta: 'Como você discerne entre a verdade e ensinos que apenas soam bem?' },
    { id: '1jo', nome: '1 João', caps: 5, autor: 'João, o apóstolo', data: '~90 d.C.',
      tema: 'Certeza da salvação: verdade, amor e vida em Cristo.',
      chave: '1Jo 4:8 — "Deus é amor."',
      panorama: 'João dá marcas de uma fé verdadeira: crer em Jesus, andar na luz e amar os irmãos. Escreve para que os crentes tenham certeza da vida eterna.',
      cristo: 'Jesus, o Filho de Deus, é a nossa vida e a propiciação pelos pecados.',
      pergunta: 'Quais sinais de fé verdadeira João aponta, e como eles aparecem em você?' },
    { id: '2jo', nome: '2 João', caps: 1, autor: 'João, o apóstolo', data: '~90 d.C.',
      tema: 'Andar na verdade e no amor.',
      chave: '2Jo 1:6 — "O amor é andarmos segundo os seus mandamentos."',
      panorama: 'Um bilhete breve: permanecer na verdade do evangelho e no amor, sem acolher quem nega a Cristo.',
      cristo: 'A verdade a ser guardada é a pessoa e a obra de Jesus.',
      pergunta: 'Como manter juntos, sem separar, o amor e a fidelidade à verdade?' },
    { id: '3jo', nome: '3 João', caps: 1, autor: 'João, o apóstolo', data: '~90 d.C.',
      tema: 'Hospitalidade e fidelidade na igreja.',
      chave: '3Jo 1:4 — "Não tenho maior alegria do que esta: ver os meus filhos andando na verdade."',
      panorama: 'João elogia Gaio pela hospitalidade e repreende Diótrefes pela arrogância. A verdade se vive em relações concretas.',
      cristo: 'Servir os irmãos por amor reflete o próprio caráter de Cristo.',
      pergunta: 'Como a hospitalidade e o serviço concreto expressam a sua fé?' },
    { id: 'jd', nome: 'Judas', caps: 1, autor: 'Judas, irmão de Tiago', data: '~65 d.C.',
      tema: 'Contender pela fé contra a apostasia.',
      chave: 'Jd 1:3 — "Batalhar pela fé que uma vez foi entregue aos santos."',
      panorama: 'Alerta urgente contra falsos mestres que distorcem a graça. Chama a permanecer firme, edificar-se na fé e guardar-se no amor de Deus.',
      cristo: 'Cristo é poderoso para guardar o crente e apresentá-lo sem culpa (1:24).',
      pergunta: 'O que significa "batalhar pela fé" sem perder a graça e o amor?' },
  ]},
  { divisao: 'Profético', testamento: 'Novo Testamento', livros: [
    { id: 'ap', nome: 'Apocalipse', caps: 22, autor: 'João, o apóstolo', data: '~95 d.C.',
      tema: 'A vitória final de Cristo e a nova criação.',
      chave: 'Ap 21:5 — "Eis que faço novas todas as coisas."',
      panorama: 'Por visões, revela Jesus glorioso reinando sobre a história. Apesar da tribulação, o mal é julgado e Deus faz novo céu e nova terra, habitando com seu povo.',
      cristo: 'Cristo é o Cordeiro e o Rei dos reis, vencedor, que consuma a redenção.',
      pergunta: 'Que esperança a promessa de Deus enxugar toda lágrima (21:4) traz para você?' },
  ]},
];
