/* ============================================================
   AS PARÁBOLAS DE CRISTO — agrupadas por tema.
   Cada parábola: n (número), t (nome), ref (onde está),
   chave (frase-chave), ctx (quando e por que Jesus contou),
   ens (o ensino central).
   ============================================================ */

window.PARABOLAS = {
  intro: 'Jesus ensinou as verdades mais profundas do Reino com histórias simples do cotidiano: sementes, ovelhas, moedas, banquetes. Uma parábola revela para quem quer entender e esconde de quem não quer. Cada uma tem uma ocasião e um alvo — saber por que Jesus a contou muda tudo.',
  blocos: [
    { id: 'p1', nome: 'O Reino de Deus', faixa: 'Parábolas 1–8', cor: 'verde', de: 1, ate: 8,
      resumo: 'Como o Reino chega, cresce escondido e vale mais do que tudo.' },
    { id: 'p2', nome: 'A graça que busca o perdido', faixa: 'Parábolas 9–13', cor: 'ouro', de: 9, ate: 13,
      resumo: 'O coração de Deus por quem se perdeu — e por quem se acha justo.' },
    { id: 'p3', nome: 'Amor, perdão e serviço', faixa: 'Parábolas 14–17', cor: 'esmeralda', de: 14, ate: 17,
      resumo: 'Como o cidadão do Reino trata o próximo.' },
    { id: 'p4', nome: 'Dinheiro e mordomia', faixa: 'Parábolas 18–23', cor: 'ambar', de: 18, ate: 23,
      resumo: 'O que fazemos com o que Deus nos confiou.' },
    { id: 'p5', nome: 'Oração e perseverança', faixa: 'Parábolas 24–25', cor: 'azul', de: 24, ate: 25,
      resumo: 'Insistir diante de um Pai que quer responder.' },
    { id: 'p6', nome: 'Vigilância e a volta de Cristo', faixa: 'Parábolas 26–30', cor: 'violeta', de: 26, ate: 30,
      resumo: 'Viver pronto para o Senhor que volta.' },
    { id: 'p7', nome: 'Israel, rejeição e juízo', faixa: 'Parábolas 31–36', cor: 'rosa', de: 31, ate: 36,
      resumo: 'Contadas na última semana: o convite recusado e o Filho rejeitado.' },
    { id: 'p8', nome: 'O novo e o custo de seguir', faixa: 'Parábolas 37–39', cor: 'azul', de: 37, ate: 39,
      resumo: 'O que muda com Jesus — e o preço de segui-lo.' },
  ],
  lista: [
    // ---------- O Reino de Deus ----------
    { n:1, t:'O semeador', ref:'Mateus 13:1-23 · Marcos 4:1-20 · Lucas 8:4-15', chave:'"Quem tem ouvidos para ouvir, ouça."',
      ctx:'Contada à multidão à beira do mar, de dentro de um barco. É a primeira grande parábola de Jesus — e a única que ele explica em detalhe, mas só aos discípulos, em particular.',
      ens:'A mesma semente (a Palavra) produz resultados diferentes conforme o solo (o coração). O problema nunca está na semente: está em como a recebemos — à beira do caminho, entre pedras, entre espinhos ou em boa terra.' },
    { n:2, t:'O joio e o trigo', ref:'Mateus 13:24-30, 36-43', chave:'"Deixai crescer ambos juntos até a ceifa."',
      ctx:'Aos discípulos, respondendo à pergunta que todos faziam: se o Reino chegou, por que o mal continua no mundo — e até no meio do povo de Deus?',
      ens:'Bem e mal coexistem até o juízo final. Não cabe a nós arrancar o joio (arriscaríamos o trigo); cabe a Deus separar, no tempo dele.' },
    { n:3, t:'A semente que cresce sozinha', ref:'Marcos 4:26-29', chave:'"A terra por si mesma frutifica."',
      ctx:'Só Marcos a registra. Contada à multidão no mesmo dia da parábola do semeador.',
      ens:'O Reino cresce pelo poder de Deus, não pelo nosso controle. Semeamos e dormimos; a semente cresce sem que saibamos como. Nosso papel é fiel, mas o crescimento é dele.' },
    { n:4, t:'O grão de mostarda', ref:'Mateus 13:31-32 · Marcos 4:30-32 · Lucas 13:18-19', chave:'"A menor de todas as sementes... torna-se árvore."',
      ctx:'À multidão, para quem esperava um Reino grandioso e imediato — e via só um carpinteiro com doze homens comuns.',
      ens:'O Reino começa insignificante e cresce além de toda expectativa, a ponto de abrigar muitos em seus ramos. Não despreze o começo pequeno.' },
    { n:5, t:'O fermento', ref:'Mateus 13:33 · Lucas 13:20-21', chave:'"Até que tudo ficasse levedado."',
      ctx:'Par da parábola da mostarda, contada logo em seguida.',
      ens:'O Reino age de dentro para fora — invisível, silencioso, mas irresistível — até transformar o todo. Assim age o Evangelho numa vida e numa sociedade.' },
    { n:6, t:'O tesouro escondido', ref:'Mateus 13:44', chave:'"Vende tudo o que tem e compra aquele campo."',
      ctx:'Aos discípulos, dentro de casa, depois de a multidão ir embora.',
      ens:'O Reino vale mais que tudo o que temos. Quem o descobre abre mão de tudo — e faz isso com alegria, não com pesar, porque sabe o que está ganhando.' },
    { n:7, t:'A pérola de grande valor', ref:'Mateus 13:45-46', chave:'"Vendeu tudo o que tinha e a comprou."',
      ctx:'Par da parábola do tesouro; também aos discípulos.',
      ens:'Uns encontram o Reino por acaso (o tesouro), outros o buscam a vida inteira (a pérola). Em ambos os casos, a resposta é a mesma: vale trocar tudo por ele.' },
    { n:8, t:'A rede', ref:'Mateus 13:47-50', chave:'"Separarão os maus dentre os justos."',
      ctx:'Encerra o sermão das parábolas, com linguagem que pescadores como Pedro e João entendiam bem.',
      ens:'Hoje o Reino recolhe de tudo, bons e maus misturados. A separação definitiva não é agora, nem é nossa — vem no fim, pelas mãos de Deus.' },

    // ---------- A graça que busca o perdido ----------
    { n:9, t:'A ovelha perdida', ref:'Lucas 15:1-7 · Mateus 18:12-14', chave:'"Haverá mais alegria no céu por um pecador que se arrepende."',
      ctx:'Os fariseus murmuravam porque Jesus recebia pecadores e comia com eles. Jesus responde com três histórias de coisas perdidas.',
      ens:'Deus busca ativamente quem se perdeu e celebra cada um que volta. Ninguém é descartável: o pastor deixa noventa e nove por uma.' },
    { n:10, t:'A moeda perdida', ref:'Lucas 15:8-10', chave:'"Alegrai-vos comigo, porque achei a dracma que tinha perdido."',
      ctx:'Mesma ocasião; a segunda das três. A mulher acende a candeia, varre a casa e procura até achar.',
      ens:'O valor do que se perdeu justifica uma busca diligente. E há festa no céu — não indiferença — pelo arrependimento de um só.' },
    { n:11, t:'O filho pródigo', ref:'Lucas 15:11-32', chave:'"Este meu filho estava morto e reviveu; estava perdido e foi achado."',
      ctx:'A terceira da série, dirigida aos fariseus: o filho mais velho, que fica de fora da festa ressentido, é o retrato deles.',
      ens:'O Pai corre ao encontro de quem volta e o restaura sem reservas. Mas há dois jeitos de estar longe do Pai: na rebeldia do mais novo e na religiosidade amarga do mais velho.' },
    { n:12, t:'Os dois devedores', ref:'Lucas 7:41-43', chave:'"Aquele a quem pouco se perdoa, pouco ama."',
      ctx:'Na casa de Simão, o fariseu, quando uma mulher conhecida como pecadora lavou os pés de Jesus com lágrimas e Simão a desprezou por dentro.',
      ens:'A medida do nosso amor revela o quanto entendemos ter sido perdoados. Quem se acha pouco devedor ama pouco.' },
    { n:13, t:'O fariseu e o publicano', ref:'Lucas 18:9-14', chave:'"Ó Deus, tem misericórdia de mim, pecador."',
      ctx:'Dirigida "a alguns que confiavam em si mesmos, crendo que eram justos, e desprezavam os outros".',
      ens:'Deus justifica o humilde que reconhece o próprio pecado — não o religioso que ora comparando-se aos outros. Quem se exalta será humilhado.' },

    // ---------- Amor, perdão e serviço ----------
    { n:14, t:'O bom samaritano', ref:'Lucas 10:25-37', chave:'"Vai e faze tu o mesmo."',
      ctx:'Um doutor da lei, "querendo justificar-se", perguntou a Jesus: "Quem é o meu próximo?"',
      ens:'Jesus inverte a pergunta: não "quem merece meu amor?", mas "de quem eu me faço próximo?". O próximo é quem precisa de mim — mesmo o inimigo cultural, como o samaritano.' },
    { n:15, t:'O servo impiedoso', ref:'Mateus 18:21-35', chave:'"Não devias tu também compadecer-te do teu conservo?"',
      ctx:'Pedro perguntou quantas vezes deveria perdoar o irmão — "até sete?". Jesus respondeu "setenta vezes sete" e contou esta história.',
      ens:'Quem foi perdoado de uma dívida impagável (dez mil talentos) não pode negar perdão a uma dívida pequena (cem denários). Receber perdão sem perdoar é contradição.' },
    { n:16, t:'O servo que fez só o dever', ref:'Lucas 17:7-10', chave:'"Somos servos inúteis; fizemos o que devíamos fazer."',
      ctx:'Aos apóstolos, logo depois de pedirem: "Aumenta-nos a fé".',
      ens:'Obedecer a Deus não gera crédito nem direito a recompensa. Serviço é dever de quem pertence ao Senhor — não moeda de troca.' },
    { n:17, t:'A candeia', ref:'Mateus 5:14-16 · Marcos 4:21-25 · Lucas 8:16-18', chave:'"Não se acende a candeia para pô-la debaixo do alqueire."',
      ctx:'No Sermão do Monte ("vós sois a luz do mundo") e repetida depois da parábola do semeador.',
      ens:'A luz recebida existe para ser vista. Fé escondida contraria a própria natureza da luz; as boas obras devem levar outros a glorificar o Pai.' },

    // ---------- Dinheiro e mordomia ----------
    { n:18, t:'O rico insensato', ref:'Lucas 12:13-21', chave:'"Louco, esta noite te pedirão a tua alma."',
      ctx:'Alguém na multidão pediu que Jesus arbitrasse uma disputa de herança. Jesus recusou e advertiu contra a avareza.',
      ens:'Acumular para si mesmo, sem ser rico para com Deus, é insensatez diante da morte certa. A vida não consiste na abundância de bens.' },
    { n:19, t:'O administrador astuto', ref:'Lucas 16:1-13', chave:'"Não podeis servir a Deus e às riquezas."',
      ctx:'Aos discípulos, enquanto os fariseus — "que eram avarentos" — ouviam e zombavam.',
      ens:'Jesus não elogia a desonestidade, mas a visão de futuro. Use o dinheiro de hoje com os olhos na eternidade; quem é fiel no pouco será fiel no muito.' },
    { n:20, t:'O rico e Lázaro', ref:'Lucas 16:19-31', chave:'"Se não ouvem a Moisés e aos profetas, tampouco se deixarão persuadir."',
      ctx:'Aos fariseus que zombavam do ensino de Jesus sobre dinheiro.',
      ens:'As escolhas desta vida têm consequências eternas e irreversíveis. E a Escritura já basta para nos avisar — quem não crê nela não creria nem num ressuscitado.' },
    { n:21, t:'Os talentos', ref:'Mateus 25:14-30', chave:'"Servo bom e fiel, sobre o pouco foste fiel."',
      ctx:'No sermão profético, no Monte das Oliveiras, poucos dias antes da cruz.',
      ens:'Deus confia dons diferentes a cada um e cobra fidelidade, não igualdade de resultados. Enterrar o que recebeu, por medo, é infidelidade.' },
    { n:22, t:'As minas', ref:'Lucas 19:11-27', chave:'"Negociai até que eu volte."',
      ctx:'Perto de Jerusalém, "porque pensavam que o Reino de Deus havia de se manifestar imediatamente".',
      ens:'Entre a partida e a volta do Rei há trabalho a fazer. Cada servo recebe o mesmo (uma mina) e responde pelo que fez com ela.' },
    { n:23, t:'Os trabalhadores da vinha', ref:'Mateus 20:1-16', chave:'"Assim os últimos serão primeiros, e os primeiros, últimos."',
      ctx:'Logo depois de Pedro perguntar: "Deixamos tudo e te seguimos — que receberemos?"',
      ens:'A recompensa de Deus é graça, não salário por hora trabalhada. Ninguém pode reclamar da generosidade dele com os que chegaram por último.' },

    // ---------- Oração e perseverança ----------
    { n:24, t:'O amigo à meia-noite', ref:'Lucas 11:5-13', chave:'"Pedi, e dar-se-vos-á; buscai, e achareis."',
      ctx:'Logo depois de ensinar o Pai Nosso, a pedido dos discípulos.',
      ens:'Se a insistência move até um amigo relutante, quanto mais o Pai — que não é relutante — e quer dar o Espírito Santo a quem pede.' },
    { n:25, t:'O juiz iníquo e a viúva', ref:'Lucas 18:1-8', chave:'"Não fará Deus justiça aos seus escolhidos, que clamam a ele?"',
      ctx:'Lucas explica o motivo: "para mostrar que devem orar sempre e nunca desanimar".',
      ens:'Persevere em oração. Deus não é como o juiz injusto — é justo e responde; a pergunta é se ele achará fé quando vier.' },

    // ---------- Vigilância e a volta de Cristo ----------
    { n:26, t:'As dez virgens', ref:'Mateus 25:1-13', chave:'"Vigiai, pois, porque não sabeis o dia nem a hora."',
      ctx:'No sermão profético, sobre a volta do Filho do Homem.',
      ens:'Preparação não se empresta na última hora. Estar pronto para o Senhor é responsabilidade pessoal e intransferível.' },
    { n:27, t:'O servo fiel e o servo mau', ref:'Mateus 24:45-51 · Lucas 12:42-48', chave:'"Bem-aventurado aquele servo a quem o senhor achar fazendo assim."',
      ctx:'Sermão profético. Em Lucas, Pedro pergunta se a parábola era para eles ou para todos.',
      ens:'A demora do Senhor testa o caráter: uns servem com fidelidade, outros abusam do poder. "A quem muito foi dado, muito se pedirá."' },
    { n:28, t:'Os servos vigilantes', ref:'Lucas 12:35-40', chave:'"Estejam cingidos os vossos lombos e acesas as vossas candeias."',
      ctx:'Aos discípulos, num ensino sobre não temer e viver pronto.',
      ens:'Prontidão constante, a qualquer hora da noite. E uma promessa surpreendente: o próprio Senhor servirá à mesa os que encontrar vigiando.' },
    { n:29, t:'A figueira que brota', ref:'Mateus 24:32-35 · Marcos 13:28-31 · Lucas 21:29-33', chave:'"Quando virdes estas coisas, sabei que ele está próximo."',
      ctx:'Sermão profético, sobre os sinais do fim.',
      ens:'Assim como os brotos da figueira anunciam o verão, os sinais anunciam a volta de Cristo. Discernir o tempo é dever do discípulo.' },
    { n:30, t:'As ovelhas e os bodes', ref:'Mateus 25:31-46', chave:'"Quando o fizestes a um destes meus pequeninos irmãos, a mim o fizestes."',
      ctx:'Encerra o sermão profético e todo o ensino público de Jesus em Mateus.',
      ens:'O juízo revela a fé verdadeira pelas obras de misericórdia feitas — ou negadas — ao faminto, ao estrangeiro, ao preso. O que fazemos ao pequenino, fazemos a Cristo.' },

    // ---------- Israel, rejeição e juízo ----------
    { n:31, t:'Os dois filhos', ref:'Mateus 21:28-32', chave:'"Os publicanos e as meretrizes entram adiante de vós no Reino de Deus."',
      ctx:'No templo, aos principais sacerdotes e anciãos que questionavam a autoridade de Jesus.',
      ens:'Obediência real vale mais que promessa vazia. O filho que disse "não" e foi é melhor que o que disse "sim" e não foi — assim os pecadores arrependidos entram antes dos religiosos.' },
    { n:32, t:'Os lavradores maus', ref:'Mateus 21:33-46 · Marcos 12:1-12 · Lucas 20:9-19', chave:'"A pedra que os construtores rejeitaram tornou-se a pedra angular."',
      ctx:'Aos líderes religiosos, na última semana. "Perceberam que falava deles" e quiseram prendê-lo.',
      ens:'Israel rejeitou os profetas e rejeitaria o Filho — e o Reino seria dado a um povo que produzisse frutos. Um retrato antecipado da cruz.' },
    { n:33, t:'O banquete de casamento', ref:'Mateus 22:1-14', chave:'"Muitos são chamados, mas poucos escolhidos."',
      ctx:'Ainda no templo, na última semana, aos líderes de Israel.',
      ens:'Recusar o convite do Rei é grave. Mas entrar sem a veste nupcial — sem a justiça que ele mesmo oferece — também é.' },
    { n:34, t:'A grande ceia', ref:'Lucas 14:15-24', chave:'"Vai pelos caminhos e atalhos e obriga-os a entrar."',
      ctx:'Num sábado, à mesa na casa de um fariseu importante, quando alguém disse: "bem-aventurado o que comer pão no Reino".',
      ens:'Desculpas triviais (campo, bois, casamento) excluem os convidados de honra. Os pobres, aleijados e desprezados enchem a casa de Deus.' },
    { n:35, t:'A figueira estéril', ref:'Lucas 13:6-9', chave:'"Deixa-a ainda este ano."',
      ctx:'Depois de notícias de tragédias (galileus mortos por Pilatos, a torre de Siloé), chamando todos ao arrependimento.',
      ens:'Deus é paciente e dá mais tempo — mas a paciência tem prazo. A árvore que não frutifica será cortada.' },
    { n:36, t:'Os dois construtores', ref:'Mateus 7:24-27 · Lucas 6:46-49', chave:'"Todo aquele que ouve estas minhas palavras e as pratica."',
      ctx:'A conclusão do Sermão do Monte.',
      ens:'Ouvir sem praticar é construir na areia. A tempestade — as provas da vida e o juízo — revela sobre que fundamento cada um edificou.' },

    // ---------- O novo e o custo de seguir ----------
    { n:37, t:'A torre e o rei', ref:'Lucas 14:28-33', chave:'"Qualquer de vós que não renuncia a tudo quanto tem não pode ser meu discípulo."',
      ctx:'Às grandes multidões que o seguiam com entusiasmo, sobre o custo real do discipulado.',
      ens:'Seguir Jesus exige calcular e aceitar o custo total — como quem constrói uma torre ou vai à guerra. Não é decisão de empolgação passageira.' },
    { n:38, t:'O remendo novo e os odres novos', ref:'Mateus 9:16-17 · Marcos 2:21-22 · Lucas 5:36-39', chave:'"Vinho novo em odres novos."',
      ctx:'Quando lhe perguntaram por que seus discípulos não jejuavam como os de João e dos fariseus.',
      ens:'O Evangelho não é remendo no judaísmo antigo, nem cabe nas estruturas velhas. O novo que Jesus traz exige formas novas.' },
    { n:39, t:'As crianças na praça', ref:'Mateus 11:16-19 · Lucas 7:31-35', chave:'"A sabedoria é justificada por seus filhos."',
      ctx:'Sobre a geração que rejeitou João Batista por ser austero demais e Jesus por ser acessível demais.',
      ens:'Quem não quer crer sempre acha um pretexto. Nenhum agrado satisfaz o coração fechado — mas os frutos revelam quem tinha razão.' },
  ],
};
